### ISSUE TITLE
Extra info on binding view-model and template in 'Basics'

### ISSUE THREAD

**Issue by dietervds** [addyosmani/backbone-fundamentals#126]
Hi,

In Basics -> Views -> Understanding render():
- Where it says '... I'm passing the markup from a template with id results-template to _.template() to be compiled..': Would it be possible to actually show results-template somewhere? It might be rather vague for newbies (such as me) as it is hard to know what that actually looks like
- Where it says '...Next, I set the html of the el DOM element to the output of processing a JSON version of the model associated with the view through the compiled template.': might it be beneficial to actually show code of associating a model with that view?

Both remarks are in the context that you're following along with the code in the book, trying to let the small examples work in your own IDE (as I'm trying to do). I get sort of stuck here since there doesn't seem anything that can actually 'do anything'. 

Just my 2 cents to provide some feedback perspective from an actual Backbone.js beginner ;-)

Cheers,

Dieter

**Comment by addyosmani** [comment]
I've been thinking about how the first section could be improved so that you have a working example by the end of it. Given that many other parts of the book use a Todo example for their workflow, would you find it useful if I swapped the gallery example with a Todo example instead? That way we could go through each block of the app explaining the concepts and the reader could then play with the app at the end of the basics section.

**Comment by dietervds** [comment]
Seems like a very good idea indeed. For me personally it doesn't really matter what the example is about, but I think the todo-app would be most convenient for you and easier to come to a working example (and more consistent with to classic to-do example).  
In either case, I find it very motivating to see the actual code work when I try to put it together myself, it's a stimulating learning experience. So I'm all for it.

**Comment by addyosmani** [comment]
We'll try addressing this in #189
