### ISSUE TITLE
To do list app example doesn't seem to work in Chrome

### ISSUE THREAD

**Issue by michaelhayman** [addyosmani/backbone-fundamentals#168]
Opening the JavaScript tools, I see these errors:
- XMLHttpRequest cannot load file:///Users/blah/Documents/Devnotes/backbone-fundamentals/practicals/modular-todo-app/js/templates/stats.html. Cross origin requests are only supported for HTTP.
- Uncaught Error: NETWORK_ERR: XMLHttpRequest Exception 101 js/libs/require/text.js: 7

**Comment by gschema** [comment]
Hi @michaelhayman,
first error basically says you need to set up development environment (server is missing in this particular case and http request should go through it) or just request url is wrong as request for the file on the system has to go trough server (in case that is the problem, you are probably looking for something along those lines "http://localhost/js/templates/stats.html" or just "/js/templates/stats.html").

Second error is caused by the first one.

Best,
Dusan

**Comment by addyosmani** [comment]
@g6scheme is correct :)
