### ISSUE TITLE
Consider adding new beginners tutorial

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#226]
@g6scheme what are your thoughts on us rewriting https://gist.github.com/fb65d21b426da11d23de into a tutorial for the book? Would this seem out of place for say, the section on RESTful app development?

**Comment by gschema** [comment]
Hi @addyosmani,
sorry for slow response, I am very busy at the moment. A lot of work and heaps of changes.

Anyways, have you thought about replacing this [Stack 1: Building A Backbone App With Node.js, Express, Mongoose and MongoDB](http://addyosmani.github.com/backbone-fundamentals/#stack-1-building-a-backbone-app-with-node.js-express-mongoose-and-mongodb) section with that tutorial or merging them or something else?

I think it could add some value as it is a bit more detailed, but not sure if its enough to justify doing it.

I think that there are few things that could add more value:
1. rewriting one of the REST examples to a bit more complex one with nested views, models handling/sharing/organization, app organization in general.
2. extending [Decoupling Backbone with the Mediator and Facade Patterns](http://addyosmani.github.com/backbone-fundamentals/#decoupling-backbone-with-the-mediator-and-facade-patterns) practical section with a more complex example, as well, which could be combined (maybe) with example in 1. into one good complex example.

These are things I hear often from people complaining that everything after the simple examples on Backbone is hard to find online.

I think such complex example would nail down the value of the book.

**Comment by addyosmani** [comment]
@g6scheme Thanks for the reply :) I was thinking of us refactoring Stack 1 into something that's a little less focused on the tools in your backend and talks more about the ideas behind moving persistance to a backend rather than localStorage/etc. I agree on 1. but I feel like this is something that would take a few weeks for us to put together. Would it be more useful for us to just show readers how to properly hook up the Todo app they created earlier to a back-end so that the data is persisting correctly? 

I know thats a lot more limited but it does get the point across. We could potentially just extract the parts from https://gist.github.com/fb65d21b426da11d23de relevant to this and apply it to the Todo app. 

Some relevant reading from others:
- http://jamesor.com/2012/04/todosmvc-backbone-nodejs-mongodb/
- http://jollyscience.com/blog/2012/04/building-your-first-restful-api-with-node-js/
- http://javascriptplayground.com/blog/2012/06/node-express-todo-app-redis

On 2. I wonder if we should outright change that chapter to be about [Aura](http://github.com/addyosmani/aura) and just make sure that the concepts are conveyed correctly about the mediator and facade patterns. This would mean we could move this chapter into the extensions one, which I feel might make more sense. 

What do you think? On Aura, we're planning on creating a good demo app for it which we could potentially turn into the example you're suggesting we use.

**Comment by AdamBrodzinski** [comment]
@addyosmani , for what it's worth I _really_ hope that https://gist.github.com/fb65d21b426da11d23de can make it into the book, or at the very least a reference link to it for beginners. It's very stripped down to the point to make it easy to see what's going on and it gradually builds up. That's the secret sauce for me... as so many other backbone tuts confused me when I was just starting (2 weeks ago), because they assumed I knew too much and went too fast. 

The [Backbone Baby Steps](http://codebyexample.info/2012/03/06/backbone-baby-steps/) which I presume this came from, is really awesome and I think now the node/express/mongodb  is something that I can now bite off... actually i'm going to try it tomorrow =)

I also attempted to start on http://addyosmani.com/blog/building-backbone-js-apps-with-ruby-sinatra-mongodb-and-haml/  a week ago or so and bailed out midway because of some backend issues... what I like about https://gist.github.com/fb65d21b426da11d23de specifically is that it eliminates any possibility of people bailing out because they're unfamiliar with node/mongodb

If it helps, i'll give you a little background on what 'category' I fall into, as many other readers may be in the same place. As of two weeks ago I had never used backbone, I had never made an 'app', and I had mediocre familiarity with the jQuery api. I a little experience with AJAX requests, and have only tinkered with rails and sinatra. I mostly worked in HTML/CSS, and had dabbled in JS to validate forms, animations, make tab containers, etc.., and now I am really diving into the 'app' side of JavaScript.

Keep up the good work!

**Comment by addyosmani** [comment]
@AdamBrodzinski I was quite fond of Baby Steps too. I found that during my JavaScript app workshops, most beginners were able to quickly grasp how to get RESTful services working with Backbone fairly quickly after going through https://gist.github.com/fb65d21b426da11d23de. 

Ideally, I'd love for us to just take what was there and rewrite it to better work with the idea of a Todo app + a backend service. I don't think it would require that much extra work. We could alternatively just try to use the article in its current state (I can speak to Björn about this). Would love to know if @g6scheme thinks there's room for us to do this or feels strongly we should go in a different direction.

**Comment by addyosmani** [comment]
Another recommendation:
- Drop Building Backbone.js Apps With Ruby, Sinatra, MongoDB and Haml
- Drop RESTful Applications
- Bring in https://gist.github.com/fb65d21b426da11d23de  as Practical 2: Writing an app with a RESTful backend
- Come up with a new RESTful chapter that contains tips practical 2 does not.

**Comment by gschema** [comment]
@addyosmani,
regarding [this tutorial](https://gist.github.com/fb65d21b426da11d23de) I think it's common sense to listen to Adam. Taking into account that:

> Another recommendation:
> - Drop Building Backbone.js Apps With Ruby, Sinatra, MongoDB and Haml
> - Drop RESTful Applications
> - Bring in https://gist.github.com/fb65d21b426da11d23de as Practical 2: Writing an app with a RESTful backend
> - Come up with a new RESTful chapter that contains tips practical 2 does not.

makes perfect sense.

Regarding:

> On 2. I wonder if we should outright change that chapter to be about Aura and just make sure that the concepts are conveyed correctly about the mediator and facade patterns. This would mean we could move this chapter into the extensions one, which I feel might make more sense.
> 
> What do you think? On Aura, we're planning on creating a good demo app for it which we could potentially turn into the example you're suggesting we use.

This would be great ("we're planning on creating a good demo app for it which we could potentially turn into the example you're suggesting we use").

**Comment by addyosmani** [comment]
I'm really glad to hear you agree @g6scheme :) I spoke to Bjorn (the author of most of the tutorial in the gist) and he's happily given us permission to use it in the book and change as much of it as we need. I think with that in mind, I might work on some commits this week that will get 3/4 of our action items above done. 

The Aura app might take a few weeks to get finalized, but I can work on making sure that we start to refactor those mediator/facade sections to fall in line with the chapter on it. I'm also expecting a new chapter on Thorax/Lumbar sometime soonish :)

**Comment by addyosmani** [comment]
@g6scheme I've just pushed https://github.com/addyosmani/backbone-fundamentals/tree/better-rest. What do you think? :)

It also addresses #231 and #232.

I'm wondering if we should bother with a later chapter on REST given that the exercise captures it well. 

![](http://addyosmani.com/gyazo/473e2.png)
