### ISSUE TITLE
Review chapter 11 - Unit Testing

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#347]
Another easy one:
- In the **Getting setup** section the link to the example SpecRunner.html is broken. The latest version of SpecRunner.html is virtually identical so its not terribly important to update it but I couldn't easily find a link to just the latest version of the file on its own.
- A lot of the tests are kind of trivial or actually end up just testing that Backbone itself works. This is absolutely fine but since this chapter is otherwise a good intro for beginners to unit testing I'd put a note in somewhere that you wouldn't normally do this.
- The sample code for the model (line 343) includes a string sanitizer but no tests for it. In a section on testing I'd skip over any sample code that isn't being tested to make things clearer. Besides which, the sanitizer is called in Todo.initialize but not when the value changes, so its not a great piece of example code anyway :)

**Comment by dcmaf** [comment]
Adding my review comments for Chapter 11 - Unit Testing here since they relate to the same chapter.

#### General

There is a "Unit Testing" header with no content after it, followed by the Jasmine header. This appears to be introducing a set of chapters on unit testing. If so, other chapters in the book should be grouped into sections as well (e.g., Core Backbone, Tools and Extensions).

The chapter ends with a header for "Unit Testing Backbone Applications With QUnit And SinonJS" followed by an Introduction section. This material could be moved, along with portions of the Jasmine introduction, to be the content of the Unit Testing section (preceding the three unit testing chapters). This would give the reader the opportunity to choose which unit testing framework they want to explore first. If not re-worked, these end sections should be moved to the QUnit chapter.

How would using RequireJS work with using Jasmine? Is that something that should be addressed in this chapter?

What does Jasmine output look like? Screenshots (like those in the QUnit chapter) would be helpful.

Consider moving unit test chapters earlier (before Tools and Extensions). I think the material is less advanced than that in the extensions and modularity chapters.

#### Detailed Comments

###### Section: Suites, Specs, & Spies
1. In discussion of spies for AJAX, the benefit of mocking server calls given is the speed. I would think the ability to simulate any response from the server would be equally important and worth noting here.
2. A detailed explanation of how the first AJAX test with spies works would be helpful. The text acknowledges that the reader may feel lost and directs them to Jasmine's online documentation, but the documentation should supplement the discussion.
3. Same applies to the second AJAX test (with a real server). It would be helpful to walk the reader through the code rather than just presenting it. For instance, why is it necessary to to wrap the expect call inside a call to run()? How does callback.callCount get set?

###### Section: beforeEach() and afterEach()

Example would be clearer if there were two specs and they relied on the state initialized by beforeEach() having been reset. Maybe change this or the earlier example which introduced declaring variables inside the suite to show how this now makes tests that require the same state independent from each other.

###### Section: Shared Scope

In the last sentence, it is unclear where the vars would be declared and where they cannot be used:

> In the previous section you may have noticed that we initially declared a variable `this.todo` in our `beforeEach()` call and were then able to continue using this in `afterEach()`. This is thanks to a powerful feature of Jasmine known as shared functional scope. Shared scope allows `this` properties to be common to all blocks (including `runs()`), but not declared variables (i.e., `var`s).

###### Section: TDD With Backbone

What is Larry Myers Backbone Koans project and why are we going to be using it? Are we going to be using the same Todo example used in the first example? If so, we should note that here (or note that this one is different for whatever reason).

After reading the chapter, the Koans project isn't mentioned until the end, so I don't think there is a need to bring it up here (in my case, it just confused me because it was introduced and then not referenced again until the very end of the chapter).

###### Section: Models

I changed the "error" event reference to "invalid".

###### Section: Initial Setup

In the last example, testing that the view's model's attributes have been initialized would appear to be a test of the model rather than the view (unless the view plays a role in initializing the model).

###### Section: Rendering with a templating system
- Provide references to the more advanced options (are we just talking about Handlebars and Mustache?) and note what features they offer that Microtemplates do not:

> However, this can get unwieldily fairly quickly. As the logic in our templates increases, so does the complexity involved. This is where templates libraries can help. As mentioned earlier, there are a number of popular options available, but for the purposes of this chapter we're going to stick to using Underscore's built-in Microtemplating. While there are more advanced options you're free to explore, the benefit of this is that no additional files are required and we can easily change the existing Jasmine specs without too much adjustment.
- Use of Microtemplate '<%= %>' tags in the examples that are using `replace()` in the render method is confusing. I had to go back and re-read before I realized that those examples were not using Microtemplates (since Microtemplates were used in the first exercise in the book). I would suggest using a different pattern to replace that does not look like an existing templating system (e.g., '+++PLACEHOLDER+++'):

> ``` javascript
> render: function() {
>   var template = '<label class="todo-content">' +
>     '<%= text %></label>';
>   var output = template
>     .replace('<%= text %>', this.model.get('text'));
>   this.$el.html(output);
>   if (this.model.get('done')) {
>     this.$('.todo-content').addClass('done');
>   }
>   return this;
> }
> ```
- Discussion of using script tags for templates seems out of place since that was covered earlier in the book and there is no example here of doing so.
- What is jasmine.yml? How do the templates in our templates directory get incorporated? It looks like we are doing a form of dependency injection by injecting the todo template. If so, some discussion along those lines would be helpful.
- What is being tested in this last example? Since we are moving the conditional rendering logic to the template, my expectation was that that would be the unit under test. However, since the template is coming from the test fixture we seem to be testing that render() passes the done flag to the template. It would be helpful to address this in the text, either by showing how the template could be tested (e.g., passing it true and false values for the done flag and verifying that the class was or wasn't added) or noting that the template logic is usually too trivial to warrant its own tests.

###### Section: Conclusions

The reference to an external source to learn about SinonJS is confusing since the book covers the subject. References to resources for it should probably be placed at the end of the chapter that discusses it.

**Comment by addyosmani** [comment]
I greatly appreciate the feedback @wibblymat and @dcmaf. What I'm going to do is work on collating the feedback on different chapters from each of the technical reviewers into chapter based issues and then address each of them individually. Unit testing seems to be one of the more straight-forward chapters to update.

**Comment by addyosmani** [comment]
> The chapter ends with a header for "Unit Testing Backbone Applications With QUnit And SinonJS" followed by an Introduction section. This material could be moved, along with portions of the Jasmine introduction, to be the content of the Unit Testing section (preceding the three unit testing chapters). This would give the reader the opportunity to choose which unit testing framework they want to explore first. If not re-worked, these end sections should be moved to the QUnit chapter.

Do you feel that there is enough material already covered to warrant a Unit testing chapter which would precede the Qunit and Jasmine ones? 

I initially had Unit testing as one chapter on it's own with both of these under it, but can reconsider.

**Comment by dcmaf** [comment]
I think it definitely makes sense to have three separate chapters (Jasmine, QUnit, and SinonJS), I think there is enough material for each to stand on its own. The QUnit chapter is almost like a QUnit primer, since it is information you need to know in order to use SinonJS with QUnit, but it really isn't Backbone-specific.

I think it might make sense to break the book up into parts, along the lines of:

Core Backbone: Fundamentals, Backbone Basics, Exercise 1, Exercise 2, Common Problems/Solutions
Unit Testing: Jasmine, QUnit, SinonJS
Modular Development: (break current content of this chapter into several chapters)
Tools and Extensions: Marionette, Thorax, Backbone Boilerplate/Grunt, Mobile Applications

Each Part would need a little half-page introduction to what is covered in that part, which is what I see preceding the unit testing chapters, rather than a complete separate chapter. For unit testing, the discussion at the end of the Jasmine chapter would fit this role and make it clear up-front that we are presenting two different unit test frameworks.

**Comment by addyosmani** [comment]
@dcmaf:

> There is a "Unit Testing" header with no content after it, followed by the Jasmine header. This appears to be introducing a set of chapters on unit testing. If so, other chapters in the book should be grouped into sections as well (e.g., Core Backbone, Tools and Extensions).

I've moved the introduction to unit testing from the Jasmine chapter, made it more generic and included it below the Unit Testing header. I like your idea about having grouped sections and am considering this further. Going down this path would make sense, but it would probably also require additional sections to be written for say, Tooling in order for each group to contain sufficient detail.

I'm going to work through the rest of your comments and questions on unit testing now. Thanks!

**Comment by addyosmani** [comment]
@dcmaf if you get a chance to look through some of the changes made, I'd love to hear if you think they've addressed your comments. I'll do another review of your notes shortly.
