### ISSUE TITLE
Review comments: Chapter 5 - Exerise 2: Book Library

### ISSUE THREAD

**Issue by dcmaf** [addyosmani/backbone-fundamentals#367]
Not too many comments on this one. I was able to work through the example and most of the issues I had are addressed by my pull request.
###### Section: Setting Up
1. I added a basic directory tree outline.
2. For the physical book, need to provide a reference to where the book cover placeholder can be downloaded from.
3. I added some clarifications of the order in which the code fragments should appear in the HTML file.
###### Section: Connecting with a third-party API

The create example could use more explanation. Is the code even correct? Why is collection.model being passed as the first parameter? How does Backbone use the attrs option?

**Comment by addyosmani** [comment]
Thanks for the review and changes to this chapter, @dcmaf. I've walked through it again and it would appear that the section on connecting with a third-party API was originally intended to be expanded on but wasn't due to some restructuring. As the tutorial stands well on it's own without this last section, I've removed it. Change incoming.
