### ISSUE TITLE
Improvement for 'The Internals'

### ISSUE THREAD

**Issue by brijcharan** [addyosmani/backbone-fundamentals#386]
Had a small improvement idea for new readers.

It would be nice to have a starter html template snippet for new users to type out, so they can run the examples in this chapter.  Right now it's not clear that they need to have more than just whats in the examples to run the code.

I would place it at the beginning of the chapter. 

The internals chapter is long, so trying the examples as you type is very valuable for new backbone programmers.

By template, I mean something like:

``` html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="http://documentcloud.github.com/underscore/underscore-min.js"></script>
<script type="text/javascript" src="http://documentcloud.github.com/backbone/backbone-min.js"></script>
<script TYPE="text/javascript">
  // Your code goes here
</script>
</body>
</html>
```

**Comment by addyosmani** [comment]
Thanks. I think this is a reasonable idea. We could also link them up to a JSBin or jsFiddle link with this boilerplate in there. @dcmaf do you think this fits well in the internals section or as a reference in the appendix which we just mention?

**Comment by addyosmani** [comment]
Given that it should be compatible with jQuery >= 1.7 I wonder if it's best to just suggest the latest version.

**Comment by dcmaf** [comment]
I actually used jsFiddle to test out all the code snippets. Since they just log to the console, you don't really even need any html. The tricky part is that you need to select jQuery under frameworks and extensions and then add Backbone and Underscore as external resources by linking to the raw versions of the source files in GitHub.

It looks like, although Backbone is not an option under frameworks/extension, that Underscore is. If you select a version of Underscore you are given options for also including Backbone (and ModelBinder and LocalStorage as well), but oddly it appears that you cannot also select jQuery, which makes it kind of useless (unless you then add jQuery as an external resource).

I concur with @brijcharan suggestion of placing it at the beginning (before the Models section). You could present the snippet above (updated to most recent versions) and explain how to set up a JSBin or jsFiddle that they can use to run the examples if they want to try them out. You may also want to note that you need to open a developer's console in the browser in order to see any output!

**Comment by addyosmani** [comment]
Thanks for your input, @dcmaf! I'm glad to hear that the examples all work in the console. Would it make more sense to present them with boilerplates that they can fork or work in for jsFiddle and jsBin? If so I've thrown the following together which I believe should work:

jsFiddle: http://jsfiddle.net/jnf8B/
jsBin: http://jsbin.com/iwiwox/1/edit

I'll throw together some paragraphs for the intro to the code sample above.

To keep in line with the boilerplates, here's the updated code:

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="http://documentcloud.github.com/underscore/underscore-min.js"></script>
<script type="text/javascript" src="http://documentcloud.github.com/backbone/backbone-min.js"></script>
<script TYPE="text/javascript">
  // Your code goes here
</script>
</body>
</html>
```

**Comment by dcmaf** [comment]
Yes, that looks good.

**Comment by addyosmani** [comment]
Done! If there's anything I've missed, please do feel free to let me know :)

**Comment by brijcharan** [comment]
Awesome @addyosmani and @dcmaf.  Loving the book btw.
