### ISSUE TITLE
"Cannot GET /" error in Exercise 2 - http://localhost:4711/

### ISSUE THREAD

**Issue by luzhang** [addyosmani/backbone-fundamentals#405]
Hi, I followed the tutorial for exercise, installed node js and npm, setup the server.js and run ''node server.js' on command line to open a port 4711. But when I tried to open http://localhost:4711/, the browser returns me the message: "Cannot GET /". Anyone knows how to fix it? I really appreciate it!  

Thanks,

Lu

**Comment by luzhang** [comment]
I figure out by myself, I installed the npm under /site directory instead of root directory. After installation, both of node_modules and site directory should be in the root directory.

**Comment by paulalden** [comment]
Im having the same issue, but my node_modules and index.html are in the root of the project.

**Comment by wbprice** [comment]
@prwhitehead were you ever able to resolve?  Running into the same issue.

**Comment by facuescobar** [comment]
This worked for me:
I added backbone examples in subdirectories, something like: localhost/backbone-examples/backbone-library/
inside that folder I have the entire site, including server.js

So I just removed "site" because I didn't use site name,
`app.use( express.static( path.join( application_root, '/') ) );`
or it could work this way too
`app.use( express.static( path.join( application_root ) ) );`

You just need to know what path is giving you the first line:
`var application_root = __dirname`
then you can decide if you need to add subdirectories.

The code has some deprecated functions, so I just updated that too, this is the entire example:

```
// Module dependencies.
var application_root = __dirname,
    express = require( 'express' ), //Web framework
    bodyParser = require('body-parser'), //Parser for reading request body
    path = require( 'path' ), //Utilities for dealing with file paths
    mongoose = require( 'mongoose' ); //MongoDB integration

//Create server
var app = express();

//Where to serve static content
app.use( express.static( path.join( application_root, '/') ) );
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

//Start server
var port = 4711;

app.listen( port, function() {
    console.log( 'Express server listening on port %d in %s mode', port, app.settings.env );
});
```

Once you have it, refresh http://localhost:4711/ 

Hope it works for you.
cheers!

**Comment by theBoringDesigner** [comment]
Fackius, you are life saver. We should probably ask addy to update his tutorial.
