### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by kofiaddaquay** [addyosmani/backbone-fundamentals#456]
page 156, the book says 
"Generally speaking, more developers opt for Solution 1 or 5 because:"...

But there is no solution 5. There are only 4 solutions here. Please advice.

page 161
this.rooms = new Rooms;

should be new Rooms();

**Comment by addyosmani** [comment]
Confirmed. I'll look into this issue further this weekend (afaik, solution 5 was dropped and I am referring to solution 4 here).

**Comment by addyosmani** [comment]
Removed.

**Comment by pjm4** [comment]
Hi Addy,

You mention that solution 4 is preferred and that 5 was dropped (and removed I take it from your last comment), however, looking at the latest version of the common problems chapter, solution 5 still appears and is also referred to as the preferred solution. Can you clarify as I myself prefer solution 4 due to its simplicity.

Thanks.

Philip
